excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://davidkatz.github.io
title: David's Blog
email: hi@davidkatz.me
author: David Katz
description: Testing description
paginate: 10
google_analytics: 