excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://davidkatz.github.io
title: David Katz
email: hi@davidkatz.me
author: David Katz
description: A blog
paginate: 10
google_analytics: 